Backend: Vivado
Board: null
ClockPeriod: 4.17
HLSConfig:
  LayerName:
    onlymu_small_compressed_4folds_hw_bitshiftscaler0_activation1:
      Precision:
        result: ap_ufixed<8,0>
      ReuseFactor: 1
    onlymu_small_compressed_4folds_hw_bitshiftscaler0_fc1:
      Precision:
        bias: ap_fixed<6,2>
        weight: ap_fixed<6,2>
      ReuseFactor: 1
    onlymu_small_compressed_4folds_hw_bitshiftscaler0_fc1_input:
      Precision:
        result: ap_fixed<16,6>
      ReuseFactor: 1
    onlymu_small_compressed_4folds_hw_bitshiftscaler0_output:
      Precision:
        bias: ap_fixed<6,2>
        weight: ap_fixed<6,2>
      ReuseFactor: 1
    onlymu_small_compressed_4folds_hw_bitshiftscaler0_sigmoid:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'models/onlymu_small_compressed_4folds_hw_bitshiftscaler_hls/model_0/keras_model.h5'
OutputDir: models/onlymu_small_compressed_4folds_hw_bitshiftscaler_hls/model_0
OutputPredictions: null
ProjectName: myproject
Stamp: C31C9cD8
XilinxPart: xcvu9p-flga2104-2L-e
