-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity TOPO_GT_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_31_14_5_3_0_config8_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_34_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_35_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_37_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_42_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_43_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_44_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_61_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_63_val : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (22 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of TOPO_GT_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_31_14_5_3_0_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv18_25A : STD_LOGIC_VECTOR (17 downto 0) := "000000001001011010";
    constant ap_const_lv18_26C : STD_LOGIC_VECTOR (17 downto 0) := "000000001001101100";
    constant ap_const_lv19_7FDA0 : STD_LOGIC_VECTOR (18 downto 0) := "1111111110110100000";
    constant ap_const_lv18_253 : STD_LOGIC_VECTOR (17 downto 0) := "000000001001010011";
    constant ap_const_lv19_7FD8F : STD_LOGIC_VECTOR (18 downto 0) := "1111111110110001111";
    constant ap_const_lv18_22E : STD_LOGIC_VECTOR (17 downto 0) := "000000001000101110";
    constant ap_const_lv18_26F : STD_LOGIC_VECTOR (17 downto 0) := "000000001001101111";
    constant ap_const_lv19_7FD70 : STD_LOGIC_VECTOR (18 downto 0) := "1111111110101110000";
    constant ap_const_lv18_232 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000110010";
    constant ap_const_lv19_7FD92 : STD_LOGIC_VECTOR (18 downto 0) := "1111111110110010010";
    constant ap_const_lv18_26A : STD_LOGIC_VECTOR (17 downto 0) := "000000001001101010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_6A2 : STD_LOGIC_VECTOR (10 downto 0) := "11010100010";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln73_fu_170_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_fu_170_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_250_fu_171_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_250_fu_171_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_245_fu_172_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_245_fu_172_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_244_fu_174_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_244_fu_174_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_248_fu_175_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_248_fu_175_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_252_fu_176_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_252_fu_176_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_247_fu_177_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_247_fu_177_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_243_fu_178_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_243_fu_178_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_251_fu_179_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_251_fu_179_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_246_fu_181_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_246_fu_181_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_249_fu_182_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_249_fu_182_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_fu_170_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_fu_838_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_243_fu_178_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln42_s_fu_857_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_244_fu_174_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_81_fu_876_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_245_fu_172_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln42_1_fu_895_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_246_fu_181_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln42_2_fu_914_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_247_fu_177_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_82_fu_933_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_248_fu_175_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln42_3_fu_952_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_249_fu_182_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_83_fu_971_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_900_fu_985_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln73_fu_993_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_901_fu_1003_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln73_fu_997_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln73_328_fu_1011_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln73_74_fu_1015_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln42_4_fu_1021_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_250_fu_171_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_84_fu_1040_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_902_fu_1054_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln73_329_fu_1062_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_903_fu_1072_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln73_75_fu_1066_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln73_330_fu_1080_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln73_76_fu_1084_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln42_5_fu_1090_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln73_251_fu_179_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_85_fu_1109_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_252_fu_176_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln70_fu_867_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln70_27_fu_886_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_fu_1138_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_fu_1144_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln70_26_fu_848_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln58_328_fu_1148_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln70_1_fu_905_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln70_2_fu_924_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_329_fu_1158_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln70_28_fu_943_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln70_3_fu_962_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_330_fu_1168_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_214_fu_1174_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln58_213_fu_1164_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln58_331_fu_1178_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln58_215_fu_1184_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln58_212_fu_1154_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln58_332_fu_1188_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_4_fu_1031_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln70_30_fu_1050_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_333_fu_1198_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_217_fu_1204_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln70_29_fu_981_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln58_334_fu_1208_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln70_5_fu_1100_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln70_31_fu_1119_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_335_fu_1218_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln_fu_1128_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_336_fu_1228_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_220_fu_1234_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln58_219_fu_1224_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln58_337_fu_1238_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln58_221_fu_1244_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln58_218_fu_1214_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln58_338_fu_1248_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln58_222_fu_1254_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln58_216_fu_1194_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_339_fu_1258_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_243_fu_178_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln73_244_fu_174_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_245_fu_172_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln73_246_fu_181_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln73_247_fu_177_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_248_fu_175_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln73_249_fu_182_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_250_fu_171_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_251_fu_179_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_252_fu_176_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_fu_170_p00 : STD_LOGIC_VECTOR (17 downto 0);

    component TOPO_GT_mul_8ns_11ns_18_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component TOPO_GT_mul_8ns_11s_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;



begin
    mul_8ns_11ns_18_1_1_U970 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_fu_170_p0,
        din1 => mul_ln73_fu_170_p1,
        dout => mul_ln73_fu_170_p2);

    mul_8ns_11ns_18_1_1_U971 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_250_fu_171_p0,
        din1 => mul_ln73_250_fu_171_p1,
        dout => mul_ln73_250_fu_171_p2);

    mul_8ns_11s_19_1_1_U972 : component TOPO_GT_mul_8ns_11s_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln73_245_fu_172_p0,
        din1 => mul_ln73_245_fu_172_p1,
        dout => mul_ln73_245_fu_172_p2);

    mul_8ns_11ns_18_1_1_U973 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_244_fu_174_p0,
        din1 => mul_ln73_244_fu_174_p1,
        dout => mul_ln73_244_fu_174_p2);

    mul_8ns_11s_19_1_1_U974 : component TOPO_GT_mul_8ns_11s_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln73_248_fu_175_p0,
        din1 => mul_ln73_248_fu_175_p1,
        dout => mul_ln73_248_fu_175_p2);

    mul_8ns_11ns_18_1_1_U975 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_252_fu_176_p0,
        din1 => mul_ln73_252_fu_176_p1,
        dout => mul_ln73_252_fu_176_p2);

    mul_8ns_11ns_18_1_1_U976 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_247_fu_177_p0,
        din1 => mul_ln73_247_fu_177_p1,
        dout => mul_ln73_247_fu_177_p2);

    mul_8ns_11s_19_1_1_U977 : component TOPO_GT_mul_8ns_11s_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln73_243_fu_178_p0,
        din1 => mul_ln73_243_fu_178_p1,
        dout => mul_ln73_243_fu_178_p2);

    mul_8ns_11ns_18_1_1_U978 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_251_fu_179_p0,
        din1 => mul_ln73_251_fu_179_p1,
        dout => mul_ln73_251_fu_179_p2);

    mul_8ns_11s_19_1_1_U979 : component TOPO_GT_mul_8ns_11s_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln73_246_fu_181_p0,
        din1 => mul_ln73_246_fu_181_p1,
        dout => mul_ln73_246_fu_181_p2);

    mul_8ns_11ns_18_1_1_U980 : component TOPO_GT_mul_8ns_11ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_249_fu_182_p0,
        din1 => mul_ln73_249_fu_182_p1,
        dout => mul_ln73_249_fu_182_p2);




    add_ln58_328_fu_1148_p2 <= std_logic_vector(signed(sext_ln58_fu_1144_p1) + signed(zext_ln70_26_fu_848_p1));
    add_ln58_329_fu_1158_p2 <= std_logic_vector(signed(sext_ln70_1_fu_905_p1) + signed(sext_ln70_2_fu_924_p1));
    add_ln58_330_fu_1168_p2 <= std_logic_vector(unsigned(zext_ln70_28_fu_943_p1) + unsigned(sext_ln70_3_fu_962_p1));
    add_ln58_331_fu_1178_p2 <= std_logic_vector(signed(sext_ln58_214_fu_1174_p1) + signed(sext_ln58_213_fu_1164_p1));
    add_ln58_332_fu_1188_p2 <= std_logic_vector(signed(sext_ln58_215_fu_1184_p1) + signed(sext_ln58_212_fu_1154_p1));
    add_ln58_333_fu_1198_p2 <= std_logic_vector(signed(sext_ln70_4_fu_1031_p1) + signed(zext_ln70_30_fu_1050_p1));
    add_ln58_334_fu_1208_p2 <= std_logic_vector(signed(sext_ln58_217_fu_1204_p1) + signed(zext_ln70_29_fu_981_p1));
    add_ln58_335_fu_1218_p2 <= std_logic_vector(signed(sext_ln70_5_fu_1100_p1) + signed(zext_ln70_31_fu_1119_p1));
    add_ln58_336_fu_1228_p2 <= std_logic_vector(unsigned(trunc_ln_fu_1128_p4) + unsigned(ap_const_lv11_6A2));
    add_ln58_337_fu_1238_p2 <= std_logic_vector(signed(sext_ln58_220_fu_1234_p1) + signed(sext_ln58_219_fu_1224_p1));
    add_ln58_338_fu_1248_p2 <= std_logic_vector(signed(sext_ln58_221_fu_1244_p1) + signed(sext_ln58_218_fu_1214_p1));
    add_ln58_339_fu_1258_p2 <= std_logic_vector(signed(sext_ln58_222_fu_1254_p1) + signed(sext_ln58_216_fu_1194_p1));
    add_ln58_fu_1138_p2 <= std_logic_vector(signed(sext_ln70_fu_867_p1) + signed(zext_ln70_27_fu_886_p1));
    ap_ready <= ap_const_logic_1;
    ap_return <= (add_ln58_339_fu_1258_p2 & ap_const_lv7_0);
    mul_ln73_243_fu_178_p0 <= mul_ln73_243_fu_178_p00(8 - 1 downto 0);
    mul_ln73_243_fu_178_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_2_val),19));
    mul_ln73_243_fu_178_p1 <= ap_const_lv19_7FD70(11 - 1 downto 0);
    mul_ln73_244_fu_174_p0 <= mul_ln73_244_fu_174_p00(8 - 1 downto 0);
    mul_ln73_244_fu_174_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_11_val),18));
    mul_ln73_244_fu_174_p1 <= ap_const_lv18_253(11 - 1 downto 0);
    mul_ln73_245_fu_172_p0 <= mul_ln73_245_fu_172_p00(8 - 1 downto 0);
    mul_ln73_245_fu_172_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_19_val),19));
    mul_ln73_245_fu_172_p1 <= ap_const_lv19_7FDA0(11 - 1 downto 0);
    mul_ln73_246_fu_181_p0 <= mul_ln73_246_fu_181_p00(8 - 1 downto 0);
    mul_ln73_246_fu_181_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_25_val),19));
    mul_ln73_246_fu_181_p1 <= ap_const_lv19_7FD92(11 - 1 downto 0);
    mul_ln73_247_fu_177_p0 <= mul_ln73_247_fu_177_p00(8 - 1 downto 0);
    mul_ln73_247_fu_177_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_34_val),18));
    mul_ln73_247_fu_177_p1 <= ap_const_lv18_26F(11 - 1 downto 0);
    mul_ln73_248_fu_175_p0 <= mul_ln73_248_fu_175_p00(8 - 1 downto 0);
    mul_ln73_248_fu_175_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_35_val),19));
    mul_ln73_248_fu_175_p1 <= ap_const_lv19_7FD8F(11 - 1 downto 0);
    mul_ln73_249_fu_182_p0 <= mul_ln73_249_fu_182_p00(8 - 1 downto 0);
    mul_ln73_249_fu_182_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_37_val),18));
    mul_ln73_249_fu_182_p1 <= ap_const_lv18_26A(11 - 1 downto 0);
    mul_ln73_250_fu_171_p0 <= mul_ln73_250_fu_171_p00(8 - 1 downto 0);
    mul_ln73_250_fu_171_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_43_val),18));
    mul_ln73_250_fu_171_p1 <= ap_const_lv18_26C(11 - 1 downto 0);
    mul_ln73_251_fu_179_p0 <= mul_ln73_251_fu_179_p00(8 - 1 downto 0);
    mul_ln73_251_fu_179_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_61_val),18));
    mul_ln73_251_fu_179_p1 <= ap_const_lv18_232(11 - 1 downto 0);
    mul_ln73_252_fu_176_p0 <= mul_ln73_252_fu_176_p00(8 - 1 downto 0);
    mul_ln73_252_fu_176_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_63_val),18));
    mul_ln73_252_fu_176_p1 <= ap_const_lv18_22E(11 - 1 downto 0);
    mul_ln73_fu_170_p0 <= mul_ln73_fu_170_p00(8 - 1 downto 0);
    mul_ln73_fu_170_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_0_val),18));
    mul_ln73_fu_170_p1 <= ap_const_lv18_25A(11 - 1 downto 0);
        sext_ln58_212_fu_1154_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_328_fu_1148_p2),15));

        sext_ln58_213_fu_1164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_329_fu_1158_p2),14));

        sext_ln58_214_fu_1174_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_330_fu_1168_p2),14));

        sext_ln58_215_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_331_fu_1178_p2),15));

        sext_ln58_216_fu_1194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_332_fu_1188_p2),16));

        sext_ln58_217_fu_1204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_333_fu_1198_p2),14));

        sext_ln58_218_fu_1214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_334_fu_1208_p2),15));

        sext_ln58_219_fu_1224_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_335_fu_1218_p2),14));

        sext_ln58_220_fu_1234_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_336_fu_1228_p2),14));

        sext_ln58_221_fu_1244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_337_fu_1238_p2),15));

        sext_ln58_222_fu_1254_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_338_fu_1248_p2),16));

        sext_ln58_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_fu_1138_p2),14));

        sext_ln70_1_fu_905_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_1_fu_895_p4),13));

        sext_ln70_2_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_2_fu_914_p4),13));

        sext_ln70_3_fu_962_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_3_fu_952_p4),13));

        sext_ln70_4_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_4_fu_1021_p4),13));

        sext_ln70_5_fu_1100_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_5_fu_1090_p4),13));

        sext_ln70_fu_867_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_s_fu_857_p4),13));

    sub_ln73_74_fu_1015_p2 <= std_logic_vector(unsigned(sub_ln73_fu_997_p2) - unsigned(zext_ln73_328_fu_1011_p1));
    sub_ln73_75_fu_1066_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(zext_ln73_329_fu_1062_p1));
    sub_ln73_76_fu_1084_p2 <= std_logic_vector(unsigned(sub_ln73_75_fu_1066_p2) - unsigned(zext_ln73_330_fu_1080_p1));
    sub_ln73_fu_997_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(zext_ln73_fu_993_p1));
    tmp_81_fu_876_p4 <= mul_ln73_244_fu_174_p2(17 downto 7);
    tmp_82_fu_933_p4 <= mul_ln73_247_fu_177_p2(17 downto 7);
    tmp_83_fu_971_p4 <= mul_ln73_249_fu_182_p2(17 downto 7);
    tmp_84_fu_1040_p4 <= mul_ln73_250_fu_171_p2(17 downto 7);
    tmp_85_fu_1109_p4 <= mul_ln73_251_fu_179_p2(17 downto 7);
    tmp_900_fu_985_p3 <= (data_42_val & ap_const_lv9_0);
    tmp_901_fu_1003_p3 <= (data_42_val & ap_const_lv2_0);
    tmp_902_fu_1054_p3 <= (data_44_val & ap_const_lv9_0);
    tmp_903_fu_1072_p3 <= (data_44_val & ap_const_lv7_0);
    tmp_fu_838_p4 <= mul_ln73_fu_170_p2(17 downto 7);
    trunc_ln42_1_fu_895_p4 <= mul_ln73_245_fu_172_p2(18 downto 7);
    trunc_ln42_2_fu_914_p4 <= mul_ln73_246_fu_181_p2(18 downto 7);
    trunc_ln42_3_fu_952_p4 <= mul_ln73_248_fu_175_p2(18 downto 7);
    trunc_ln42_4_fu_1021_p4 <= sub_ln73_74_fu_1015_p2(18 downto 7);
    trunc_ln42_5_fu_1090_p4 <= sub_ln73_76_fu_1084_p2(18 downto 7);
    trunc_ln42_s_fu_857_p4 <= mul_ln73_243_fu_178_p2(18 downto 7);
    trunc_ln_fu_1128_p4 <= mul_ln73_252_fu_176_p2(17 downto 7);
    zext_ln70_26_fu_848_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_838_p4),14));
    zext_ln70_27_fu_886_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_81_fu_876_p4),13));
    zext_ln70_28_fu_943_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_82_fu_933_p4),13));
    zext_ln70_29_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_83_fu_971_p4),14));
    zext_ln70_30_fu_1050_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_84_fu_1040_p4),13));
    zext_ln70_31_fu_1119_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_85_fu_1109_p4),13));
    zext_ln73_328_fu_1011_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_901_fu_1003_p3),19));
    zext_ln73_329_fu_1062_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_902_fu_1054_p3),19));
    zext_ln73_330_fu_1080_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_903_fu_1072_p3),19));
    zext_ln73_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_900_fu_985_p3),19));
end behav;
