-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity topo_HHbbWW_1mu_v5_linear_ap_fixed_16_6_4_0_0_ap_fixed_16_6_5_3_0_linear_config9_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of topo_HHbbWW_1mu_v5_linear_ap_fixed_16_6_4_0_0_ap_fixed_16_6_5_3_0_linear_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= data_val;
end behav;
