-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity topo_HHbbWW_1mu_v5_sigmoid_ap_fixed_31_14_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_val : IN STD_LOGIC_VECTOR (22 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of topo_HHbbWW_1mu_v5_sigmoid_ap_fixed_31_14_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config10_s is
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv13_200 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal sigmoid_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln121_fu_185_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sigmoid_table_ce0_local : STD_LOGIC;
    signal tmp_3_fu_69_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln115_fu_91_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_95_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln115_fu_79_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln115_fu_103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln115_fu_109_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_83_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_fu_115_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_round_fu_123_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_fu_131_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln113_fu_137_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_1_fu_141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_1_fu_149_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_4_fu_161_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln119_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln113_fu_157_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_2_fu_177_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component topo_HHbbWW_1mu_v5_sigmoid_ap_fixed_31_14_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config10_s_sigmoid_tbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    sigmoid_table_U : component topo_HHbbWW_1mu_v5_sigmoid_ap_fixed_31_14_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config10_s_sigmoid_tbkb
    generic map (
        DataWidth => 10,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_table_address0,
        ce0 => sigmoid_table_ce0_local,
        q0 => sigmoid_table_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 =>
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln115_fu_109_p2 <= std_logic_vector(signed(sext_ln115_fu_79_p1) + signed(ap_const_lv13_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            ap_done <= ap_const_logic_1;
        else
            ap_done <= ap_const_logic_0;
        end if;
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            ap_idle <= ap_const_logic_1;
        else
            ap_idle <= ap_const_logic_0;
        end if;
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then
            ap_idle_pp0 <= ap_const_logic_1;
        else
            ap_idle_pp0 <= ap_const_logic_0;
        end if;
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if;
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            ap_ready <= ap_const_logic_1;
        else
            ap_ready <= ap_const_logic_0;
        end if;
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if;
    end process;

    ap_return <= sigmoid_table_q0;
    data_round_fu_123_p3 <=
        select_ln115_fu_115_p3 when (tmp_fu_83_p3(0) = '1') else
        sext_ln115_fu_79_p1;
    icmp_ln115_fu_103_p2 <= "0" when (tmp_2_fu_95_p3 = ap_const_lv17_0) else "1";
    icmp_ln119_fu_171_p2 <= "0" when (tmp_4_fu_161_p4 = ap_const_lv3_0) else "1";
    index_1_fu_149_p3 <=
        ap_const_lv13_0 when (tmp_1_fu_141_p3(0) = '1') else
        index_fu_131_p2;
    index_2_fu_177_p3 <=
        ap_const_lv10_3FF when (icmp_ln119_fu_171_p2(0) = '1') else
        trunc_ln113_fu_157_p1;
    index_fu_131_p2 <= std_logic_vector(unsigned(data_round_fu_123_p3) + unsigned(ap_const_lv13_200));
    select_ln115_fu_115_p3 <=
        add_ln115_fu_109_p2 when (icmp_ln115_fu_103_p2(0) = '1') else
        sext_ln115_fu_79_p1;
        sext_ln113_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(index_fu_131_p2),21));

        sext_ln115_fu_79_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_69_p4),13));

    sigmoid_table_address0 <= zext_ln121_fu_185_p1(10 - 1 downto 0);

    sigmoid_table_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            sigmoid_table_ce0_local <= ap_const_logic_1;
        else
            sigmoid_table_ce0_local <= ap_const_logic_0;
        end if;
    end process;

    tmp_1_fu_141_p3 <= sext_ln113_fu_137_p1(20 downto 20);
    tmp_2_fu_95_p3 <= (trunc_ln115_fu_91_p1 & ap_const_lv6_0);
    tmp_3_fu_69_p4 <= data_val(22 downto 11);
    tmp_4_fu_161_p4 <= index_1_fu_149_p3(12 downto 10);
    tmp_fu_83_p3 <= data_val(22 downto 22);
    trunc_ln113_fu_157_p1 <= index_1_fu_149_p3(10 - 1 downto 0);
    trunc_ln115_fu_91_p1 <= data_val(11 - 1 downto 0);
    zext_ln121_fu_185_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_2_fu_177_p3),64));
end behav;
