-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity topo_HHbbWW_1mu_v5_relu_ap_fixed_31_14_5_3_0_ap_fixed_16_6_4_0_0_relu_config10_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_val : IN STD_LOGIC_VECTOR (22 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of topo_HHbbWW_1mu_v5_relu_ap_fixed_31_14_5_3_0_ap_fixed_16_6_4_0_0_relu_config10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal trunc_ln46_fu_74_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_789_fu_84_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_78_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_788_fu_66_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_56_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_fu_104_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_fu_108_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_790_fu_114_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_48_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_395_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_fu_134_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_fu_42_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_395_fu_142_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    add_ln46_fu_108_p2 <= std_logic_vector(unsigned(trunc_ln_fu_56_p4) + unsigned(zext_ln46_fu_104_p1));
    and_ln46_fu_98_p2 <= (tmp_788_fu_66_p3 and or_ln46_fu_92_p2);
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln46_395_fu_142_p3 when (icmp_ln45_fu_42_p2(0) = '1') else 
        ap_const_lv16_0;
    icmp_ln45_fu_42_p2 <= "1" when (signed(data_val) > signed(ap_const_lv23_0)) else "0";
    icmp_ln46_fu_78_p2 <= "0" when (trunc_ln46_fu_74_p1 = ap_const_lv6_0) else "1";
    or_ln46_395_fu_122_p2 <= (tmp_fu_48_p3 or tmp_790_fu_114_p3);
    or_ln46_fu_92_p2 <= (tmp_789_fu_84_p3 or icmp_ln46_fu_78_p2);
    select_ln46_395_fu_142_p3 <= 
        select_ln46_fu_134_p3 when (or_ln46_395_fu_122_p2(0) = '1') else 
        add_ln46_fu_108_p2;
    select_ln46_fu_134_p3 <= 
        ap_const_lv16_7FFF when (xor_ln46_fu_128_p2(0) = '1') else 
        ap_const_lv16_8000;
    tmp_788_fu_66_p3 <= data_val(6 downto 6);
    tmp_789_fu_84_p3 <= data_val(7 downto 7);
    tmp_790_fu_114_p3 <= add_ln46_fu_108_p2(15 downto 15);
    tmp_fu_48_p3 <= data_val(22 downto 22);
    trunc_ln46_fu_74_p1 <= data_val(6 - 1 downto 0);
    trunc_ln_fu_56_p4 <= data_val(22 downto 7);
    xor_ln46_fu_128_p2 <= (tmp_fu_48_p3 xor or_ln46_395_fu_122_p2);
    zext_ln46_fu_104_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln46_fu_98_p2),16));
end behav;
