set_property BEL A6LUT [get_cells {readout/bunch_ctr_i[1]_i_1}]
set_property BEL A5LUT [get_cells {readout/bunch_ctr_i[2]_i_1}]
set_property BEL A6LUT [get_cells {readout/dbus_evt_ctr[12]_i_5}]
set_property BEL C6LUT [get_cells {readout/dbus_evt_ctr[0]_i_12}]
set_property LOC SLICE_X143Y466 [get_cells {readout/dbus_evt_ctr[12]_i_5}]
set_property LOC SLICE_X140Y477 [get_cells {readout/bunch_ctr_i[2]_i_1}]
set_property LOC SLICE_X142Y466 [get_cells {readout/dbus_evt_ctr[0]_i_12}]
set_property LOC SLICE_X140Y477 [get_cells {readout/bunch_ctr_i[1]_i_1}]
