# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ugt-build/bergauer/github/cms-l1-globaltrigger/mp7_ugt_legacy/firmware/ngc/rom_lut_muon_inv_dr_sq_6/rom_lut_muon_inv_dr_sq_6.xci
# IP: The module: 'rom_lut_muon_inv_dr_sq_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ugt-build/bergauer/github/cms-l1-globaltrigger/mp7_ugt_legacy/firmware/ngc/rom_lut_muon_inv_dr_sq_6/rom_lut_muon_inv_dr_sq_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_lut_muon_inv_dr_sq_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ugt-build/bergauer/github/cms-l1-globaltrigger/mp7_ugt_legacy/firmware/ngc/rom_lut_muon_inv_dr_sq_6/rom_lut_muon_inv_dr_sq_6.xci
# IP: The module: 'rom_lut_muon_inv_dr_sq_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ugt-build/bergauer/github/cms-l1-globaltrigger/mp7_ugt_legacy/firmware/ngc/rom_lut_muon_inv_dr_sq_6/rom_lut_muon_inv_dr_sq_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_lut_muon_inv_dr_sq_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
